-- Matières IFRI (EC) sans accents
-- Generé automatiquement — 119 matieres

TRUNCATE TABLE competences RESTART IDENTITY CASCADE;

INSERT INTO competences (nom, categorie) VALUES
('Administration de bases de donnees', 'General'),
('Administration des reseaux sous Windows/Linux', 'General'),
('Administration des serveurs Linux', 'General'),
('Administration des serveurs Windows', 'General'),
('Administration des services sous Linux/UNIX', 'General'),
('Administration des services sous Windows', 'General'),
('Administration systemes et reseaux sous Linux', 'General'),
('Administration systemes et reseaux sous Windows', 'General'),
('Algorithmes avances', 'General'),
('Algorithmique', 'General'),
('Algebre lineaire et applications', 'General'),
('Analyse combinatoire et calcul des probabilites', 'General'),
('Analyse des evenements de securite', 'General'),
('Analyse et applications', 'General'),
('Analyse et conception orientee objet', 'General'),
('Anglais pour la communication scientifique', 'General'),
('Anglais technique', 'General'),
('Application avec les langages Java et C++', 'General'),
('Architecture et topologie des reseaux informatiques', 'General'),
('Architecture logicielle', 'General'),
('Aspects avances des bases de donnees', 'General'),
('Aspects avances des technologies web', 'General'),
('Aspects juridiques lies aux TIC', 'General'),
('Assurance qualite et test logiciel', 'General'),
('Atelier-Seminaire de developpement logiciel', 'General'),
('Audit de securite du SI', 'General'),
('Audit de systemes informatiques', 'General'),
('Audit et normes de securite', 'General'),
('Bases de donnees avancees', 'General'),
('Bases de donnees distribuees', 'General'),
('Bases de donnees multimedia et web semantique', 'General'),
('Bases de donnees relationnelles et mySQL', 'General'),
('Bases du genie logiciel', 'General'),
('Communication manageriale', 'General'),
('Communication en Anglais', 'General'),
('Commutation et routage', 'General'),
('Conduite de projets informatiques', 'General'),
('Cryptographie', 'General'),
('Cryptographie et applications', 'General'),
('Cycle de vie et methodes de developpement logiciel', 'General'),
('Data Mining', 'General'),
('Deontologie et droit lies aux TIC', 'General'),
('Developpement web', 'General'),
('Entreprenariat et plan d''affaires', 'General'),
('Etude des protocoles', 'General'),
('Filtrage des acces', 'General'),
('Fondamentaux des big data', 'General'),
('Gestion de projets informatiques', 'General'),
('Gestion des risques et incidents', 'General'),
('Gouvernance de la securite du Systeme d''information', 'General'),
('Infographie', 'General'),
('Ingenierie Logicielle et les PGI/ERP', 'General'),
('Interconnexion LAN en WAN', 'General'),
('Interfaces homme-machine', 'General'),
('Introduction aux reseaux de neurones artificiels', 'General'),
('Introduction a l''Intelligence Artificielle', 'General'),
('Introduction a l''Internet des Objets', 'General'),
('Introduction a la Blockchain', 'General'),
('Kubernetes, Serverless et Service Mesh', 'General'),
('Langage C', 'General'),
('Logique et arithmetique', 'General'),
('Maintenance des appareils electroniques', 'General'),
('Management de la securite du systeme d''information', 'General'),
('Mathematiques pour informatique', 'General'),
('Methode Agile Scrum', 'General'),
('Methodes d''analyse et de conception', 'General'),
('Methodes et outils de visualisation de donnees', 'General'),
('Methodologie d''audit du Systeme d''Informations', 'General'),
('Methodologie de redaction de memoire', 'General'),
('Normes et architectures des reseaux sans fil', 'General'),
('Outils de Java', 'General'),
('Outils de Python et R', 'General'),
('Outils de base en informatique', 'General'),
('Politique de securite des systemes d''information', 'General'),
('Programmation avancee en Python et R', 'General'),
('Programmation graphique en Qt/C++', 'General'),
('Programmation graphique et evenementielle Java', 'General'),
('Programmation Python', 'General'),
('Projet d''application', 'General'),
('Projet de validation des acquis en Java', 'General'),
('Projet integrateur', 'General'),
('Protocoles WEP, WPA, WPS', 'General'),
('Protocoles de routage et securite', 'General'),
('Recherche operationnelle', 'General'),
('Routage WAN et securite', 'General'),
('Reseaux de capteurs sans fils et IoT', 'General'),
('Reseaux informatiques et protocoles de routage', 'General'),
('SGBD et langage SQL', 'General'),
('Specification des logiciels', 'General'),
('Statistiques inferentielles et applications', 'General'),
('Structure de donnees avancees', 'General'),
('Structure de donnees et applications avec C/Python', 'General'),
('Structures algebriques et leurs applications', 'General'),
('Suites et series numeriques', 'General'),
('Systeme d''information decisionnel', 'General'),
('Systemes repartis et mobiles', 'General'),
('Systemes repartis, embarques et temps reel', 'General'),
('Securisation des bases de donnees et des programmes', 'General'),
('Securite Mobile (OWASP)', 'General'),
('Securite Web (OWASP)', 'General'),
('Securite des applications et reverse engineering', 'General'),
('Securite des systemes d''information', 'General'),
('Securite des systemes informatiques', 'General'),
('Securite et fiabilite des systemes d''information', 'General'),
('Techniques avancees avec les reseaux de neurones', 'General'),
('Techniques d''expression ecrite et orale', 'General'),
('Technologie de la Blockchain et Applications', 'General'),
('Technologie des Reseaux sans fil (WLAN & WWAN)', 'General'),
('Technologie et securite du Cloud Computing', 'General'),
('Technologies avancees mobile', 'General'),
('Technologies avancees web', 'General'),
('Technologies et pratiques du DevSecOps', 'General'),
('Tests de securite', 'General'),
('Theorie des bases de donnees et algebre relationnelle', 'General'),
('Theorie des graphes et applications', 'General'),
('Theorie des langages', 'General'),
('Traitement du signal et d''image', 'General'),
('Utilisation et administration sous Windows/Linux', 'General'),
('Equations differentielles et calcul integral', 'General');